version: "3.9"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: test
      MARIADB_USER: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
