version: "3.9"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dev
    volumes:
      - db-volume:/data/db
      - ./db-backup:/tmp/db-backup
  mongo-express:
    image: mongo-express
    ports:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
volumes:
  db-volume:
